name = "joshuaswickcom"
main = "./.output/server/index.mjs"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm run build"

[assets]
binding = "ASSETS"
directory = "./.output/public"
